[package]
name = "syn-rsx"
description = "syn-powered parser for JSX-like TokenStreams"
version = "0.4.1"
authors = ["stoically <stoically@protonmail.com>"]
keywords = ["syn", "jsx", "rsx", "html", "macro"]
edition = "2018"
repository = "https://github.com/stoically/syn-rsx"
readme = "README.md"
license = "MIT"

[dependencies]
proc-macro2 = "1.0.18"
syn = { version = "1.0.30", features = ["full", "parsing", "extra-traits"] }

[dev-dependencies]
quote = "1.0.6"
