[package]
name = "syn-rsx"
description = "syn-powered parser for JSX-like TokenStreams"
version = "0.7.2"
authors = ["stoically <stoically@protonmail.com>"]
keywords = ["syn", "jsx", "rsx", "html", "macro"]
edition = "2018"
repository = "https://github.com/stoically/syn-rsx"
readme = "README.md"
license = "MIT"

[lib]
bench = false

[dependencies]
proc-macro2 = "1.0.20"
quote = "1.0.7"
syn = { version = "1.0.39", features = ["full", "parsing", "extra-traits"] }

[dev-dependencies]
criterion = "=0.3.2"

[[bench]]
name = "bench"
harness = false

[workspace]
members = [
    "examples/html-to-string-macro"
]
