[package]
name = "html-to-string-macro"
version = "0.1.0"
authors = ["stoically <stoically@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.20"
quote = "1.0.7"
syn-rsx = { version = "0.7.1", path = "../.." }
